### ISSUE TITLE
Error inflating class com.suke.widget.SwitchButton

### ISSUE THREAD

**Issue by RajibBiswas** [zcweng/SwitchButton#1]
FATAL EXCEPTION: main
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.improlabs.optima.ucs/com.improlabs.optima.ucs.MainActivity}: android.view.InflateException: Binary XML file line #185: Error inflating class com.suke.widget.SwitchButton
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: android.view.InflateException: Binary XML file line #185: Error inflating class com.suke.widget.SwitchButton
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                              at com.improlabs.optima.fragments.SettingsFragment.onCreateView(SettingsFragment.java:80)
                                                                              at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
                                                                              at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
                                                                              at android.app.Activity.performStart(Activity.java:5018)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                              at android.os.Looper.loop(Looper.java:137) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by zcweng** [comment]
是在fragment里使用出现的异常吗？

**Comment by XiePeiXuan** [comment]
recyclerview也有

**Comment by fengjue** [comment]
@Override
    public final void setPadding(int left, int top, int right, int bottom) {
        //do nothing
        throw new RuntimeException("illegal call : method [setPadding]");
    }
想请教一下，这段代码的作用是什么？

**Comment by fengjue** [comment]
还有我感觉上面的异常是由于setPadding的时候引发的

**Comment by msdx** [comment]
Same problem in my project:
```
03-16 14:12:27.367 30767-30767/com.parkingwang.iop E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.parkingwang.iop/com.parkingwang.iop.core.summary.DataSummaryAty}: android.view.InflateException: Binary XML file line #8: Error inflating class com.parkingwang.iop.widgets.uis.LineChart
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2081)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:137)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4819)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.parkingwang.iop.widgets.uis.LineChart
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:683)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:816)
                                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:900)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:559)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:417)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:122)
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:118)
                                                                         at com.parkingwang.iop.core.summary.DataSummaryAty.setUpContentView(DataSummaryAty.java:109)
                                                                         at com.parkingwang.iop.base.BaseActivity.onCreate(BaseActivity.java:75)
                                                                         at android.app.Activity.performCreate(Activity.java:5084)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:137) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4819) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:816) 
                                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:900) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:559) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:417) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:122) 
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:118) 
                                                                         at com.parkingwang.iop.core.summary.DataSummaryAty.setUpContentView(DataSummaryAty.java:109) 
                                                                         at com.parkingwang.iop.base.BaseActivity.onCreate(BaseActivity.java:75) 
                                                                         at android.app.Activity.performCreate(Activity.java:5084) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:137) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4819) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class com.suke.widget.SwitchButton
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:683)
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:816)
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:559)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:417)
                                                                         at com.parkingwang.iop.widgets.uis.LineChart.setUpView(LineChart.java:69)
                                                                         at com.parkingwang.iop.widgets.uis.LineChart.<init>(LineChart.java:60)
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                         at android.view.LayoutInflater.createView(LayoutInflater.java:657) 
                                                                         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:816) 
                                                                         at android.view.LayoutInflater.parseInclude(LayoutInflater.java:900) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.rInflate(LayoutInflater.java:819) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:559) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:417) 
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:122) 
                                                                         at com.parkingwang.iop.base.BaseActivity.setContentView(BaseActivity.java:118) 
                                                                         at com.parkingwang.iop.core.summary.DataSummaryAty.setUpContentView(DataSummaryAty.java:109) 
                                                                         at com.parkingwang.iop.base.BaseActivity.onCreate(BaseActivity.java:75) 
                                                                         at android.app.Activity.performCreate(Activity.java:5084) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
                                                                         at android.app.ActivityThread.access$600(ActivityThread.java:137) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:4819) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                         at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                         at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                     	at android.view.LayoutInflater.createView(LayoutInflater.j
```

Android 4.1.2

**Comment by msdx** [comment]
The crash also happened when your sample project was run on Android 4.1.2.
```
E/AndroidRuntime: FATAL EXCEPTION: main
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.suke.widget.sample/com.suke.widget.sample.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.suke.widget.SwitchButton
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2081)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
  at android.app.ActivityThread.access$600(ActivityThread.java:137)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:4819)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
  at dalvik.system.NativeStart.main(Native Method)
  Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.suke.widget.SwitchButton
  at android.view.LayoutInflater.createView(LayoutInflater.java:683)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:816)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:559)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:417)
  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:328)
  at android.app.Activity.setContentView(Activity.java:1942)
  at com.suke.widget.sample.MainActivity.onCreate(MainActivity.java:12)
  at android.app.Activity.performCreate(Activity.java:5084)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
  at android.app.ActivityThread.access$600(ActivityThread.java:137) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:137) 
  at android.app.ActivityThread.main(ActivityThread.java:4819) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:511) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
  at dalvik.system.NativeStart.main(Native Method) 
  Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Constructor.constructNative(Native Method)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
  at android.view.LayoutInflater.createView(LayoutInflater.java:657)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757) 
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:816) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:559) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:417) 
  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:328) 
  at android.app.Activity.setContentView(Activity.java:1942) 
  at com.suke.widget.sample.MainActivity.onCreate(MainActivity.java:12) 
  at android.app.Activity.performCreate(Activity.java:5084) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
  at android.app.ActivityThread.access$600(ActivityThread.java:137) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:137) 
  at android.app.ActivityThread.main(ActivityThread.java:4819) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:511) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
  at dalvik.system.NativeStart.main(Native Method) 
  Caused by: java.lang.RuntimeException: illegal call : method [setPadding]
  at com.suke.widget.SwitchButton.setPadding(SwitchButton.java:68)
  at android.view.View.<init>(View.java:3741)
  at android.view.View.<init>(View.java:3355)
  at com.suke.widget.SwitchButton.<init>(SwitchButton.java:50)
  at java.lang.reflect.Constructor.constructNative(Native Method) 
  at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
  at android.view.LayoutInflater.createView(LayoutInflater.java:657) 
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757) 
  at android.view.LayoutInflater.rInflate(LayoutInflater.java:816) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:559) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
  at android.view.LayoutInflater.inflate(LayoutInflater.java:417) 
  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:328) 
  at android.app.Activity.setContentView(Activity.java:1942) 
  at com.suke.widget.sample.MainActivity.onCreate(MainActivity.java:12) 
  at android.app.Activity.performCreate(Activity.java:5084) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) 
  at android.app.ActivityThread.access$600(ActivityThread.java:137) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:137) 
  at android.app.ActivityThread.main(ActivityThread.java:4819) 
  at java.lang.reflect.Method.invokeNative(Native Method) 
  at java.lang.reflect.Method.invoke(Method.java:511) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
  at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by msdx** [comment]
@fengjue You are right. The crash was caused by the overwritten method `setPadding` that throw a RuntimeException.
I dump the stack and found this method would be call by `View.recomputePadding()` method:
```
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err: java.lang.Throwable: stack dump
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at java.lang.Thread.dumpStack(Thread.java:496)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at com.suke.widget.SwitchButton.setPadding(SwitchButton.java:69)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.View.recomputePadding(View.java:11006)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.View.resolvePadding(View.java:11676)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.View.onAttachedToWindow(View.java:11533)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.View.dispatchAttachedToWindow(View.java:11874)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2537)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2537)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2537)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2537)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1274)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1072)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4297)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:555)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:525)
03-16 14:42:24.067 4359-4359/com.suke.widget.sample W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:615)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at android.os.Looper.loop(Looper.java:137)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4819)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
03-16 14:42:24.077 4359-4359/com.suke.widget.sample W/System.err:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by fengjue** [comment]
@zcweng  can you speak chinese?Yes,this quetion happened in android 4.1.2,but i do not understand why it is happened in 16 not more than 17.

**Comment by hyoungtaikkim** [comment]
Same problem happens in Android 8.0.0. FYI, the error message is exactly same as the above msdx's.
